# pylint: disable=no-member,invalid-name,unused-import

"""UserRole

Revision ID: b4954e3e6909
Revises: 06b996e3fd46
Create Date: 2022-08-28 10:11:40.776243

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import common.datatypes.database


# revision identifiers, used by Alembic.
revision = "b4954e3e6909"
down_revision = "06b996e3fd46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userrole",
        sa.Column(
            "id",
            common.datatypes.database.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", common.datatypes.database.GUID(), nullable=False),
        sa.Column("role_id", common.datatypes.database.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id"),
    )
    op.create_index(op.f("ix_userrole_user_id"), "userrole", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userrole_user_id"), table_name="userrole")
    op.drop_table("userrole")
    # ### end Alembic commands ###
