version: "3.9"

x-common-args: &common-args
  DEPLOYMENT_ENVIRONMENT: production

services:
  api:
    build:
      context: infrastructure/api
      args: *common-args

  identity:
    build:
      context: src/service/identity
      args: *common-args

  reader:
    build:
      context: src/service/reader
      args: *common-args

  reviewer:
    build:
      context: src/service/reviewer
      args: *common-args

  administrator:
    build:
      context: src/service/administrator
      args: *common-args

  core:
    build:
      context: src/service/core
      args: *common-args

  front-end-base:
    build:
      context: src/front-end
      args: *common-args

  front-end-react:
    build:
      context: src/front-end
      args:
        DEPLOYMENT_ENVIRONMENT: ci
