version: "3.9"

x-common-args: &common-args
  DEPLOYMENT_ENVIRONMENT: production

services:
  api:
    build:
      context: api
      args: *common-args

  be-identity:
    build:
      context: be-identity
      args: *common-args

  be-reader:
    build:
      context: be-reader
      args: *common-args

  be-reviewer:
    build:
      context: be-reviewer
      args: *common-args

  be-administrator:
    build:
      context: be-administrator
      args: *common-args
