#!/usr/bin/env bash

BACKENDS=(identity reader reviewer administrator)
DIRECTORIES=(common database)
FILES=(Dockerfile .dockerignore alembic.ini)

for BACKEND in "${BACKENDS[@]}"
do
  TARGET=be-${BACKEND}

  for DIRECTORY in "${DIRECTORIES[@]}"
  do
    rsync -v -r -d --delete --delete-excluded be-common/${DIRECTORY} ${TARGET}
  done

  for FILE in "${FILES[@]}"
  do
    cp -v be-common/${FILE} ${TARGET}
  done
done

# reader is unauthenticated
echo
echo "removing unused files..."
rm -fv be-reader/common/services/authorization.py
rm -rfv be-reader/database/migrations
rm -rfv be-reviewer/database/migrations
rm -rfv be-administrator/database/migrations
rm -fv be-reader/alembic.ini
rm -fv be-reviewer/alembic.ini
rm -fv be-administrator/alembic.ini
