#!/usr/bin/env bash

BACKENDS=(identity reader reviewer administrator)
DIRECTORIES=(common database)
FILES=(Dockerfile .dockerignore alembic.ini)

for BACKEND in "${BACKENDS[@]}"
do
  TARGET=be-${BACKEND}

  for DIRECTORY in "${DIRECTORIES[@]}"
  do
    rsync -v -r -d --delete --delete-excluded be-common/${DIRECTORY} ${TARGET}
  done

  for FILE in "${FILES[@]}"
  do
    cp -v be-common/${FILE} ${TARGET}
  done
done

# identity doesn't need to authenticate JWT tokens, it creates them
# reader is unauthenticated
echo
rm -v be-reader/common/services/authentication.py
rm -v be-identity/common/services/authentication.py
