version: 2.1

x-docker-auth: &docker-auth
  username: $DOCKERHUB_USER
  password: $DOCKERHUB_ACCESS_TOKEN

x-black-steps: &black-steps
  - run:
      name: Login to DockerHub
      command: docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_ACCESS_TOKEN}"
  - run:
      name: Install test dependencies
      command: poetry install --no-root --with test
  - run:
      name: Blacken
      command: black .
  - run:
      name: Confirm unchanged
      command: |
        [[ -z "$(git status --porcelain)" ]] || false


jobs:
  build_and_push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Update package manager
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt-get -y install rsync
      - run:
          name: Sync common code
          command: ./scripts/sync
      - run:
          name: Build images from docker-compose.yml
          command: docker compose -f production-compose.yml build
      - run:
          name: Tag images
          command: |
            IMAGES=(api identity reader reviewer administrator)

            for IMAGE in "${IMAGES[@]}"; do
              TAG="${IMAGE}-${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
              docker tag "project_${IMAGE}:latest" "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${TAG}"

              TAG="${IMAGE}-${CIRCLE_BRANCH}-latest"
              docker tag "project_${IMAGE}:latest" "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${TAG}"
            done
      - run:
          name: Login to DockerHub
          command: docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_ACCESS_TOKEN}"
      - run:
          name: Push images
          command: |
            IMAGES=(api identity reader reviewer administrator)

            for IMAGE in "${IMAGES[@]}"; do
              TAG="${IMAGE}-${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
              docker push "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${TAG}"

              TAG="${IMAGE}-${CIRCLE_BRANCH}-latest"
              docker push "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${TAG}"
            done

  black-identity:
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:identity-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *black-steps

  black-administrator:
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:administrator-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *black-steps

  black-reviewer:
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:reviewer-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *black-steps

  black-reader:
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:reader-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *black-steps

workflows:
  everything:
    jobs:
      - hold:
          type: approval
      - build_and_push:
          requires:
            - hold
      - black-identity:
          requires:
            - build_and_push
      - black-administrator:
          requires:
            - build_and_push
      - black-reviewer:
          requires:
            - build_and_push
      - black-reader:
          requires:
            - build_and_push
