version: 2.1

x-docker-auth: &docker-auth
  username: $DOCKERHUB_USER
  password: $DOCKERHUB_ACCESS_TOKEN

x-black-steps: &black-steps
  - run:
      name: Install git
      command: apt-get -y install git
  - run:
      name: Install test dependencies
      command: |
        cd /app
        poetry install --no-root --with test
  - run:
      name: Blacken
      command: |
        . /root/.cache/pypoetry/virtualenvs/*/bin/activate
        cd /app
        black .
        [[ -z "$(git status --porcelain)" ]] || false

x-pytest-steps: &pytest-steps
  - run:
      name: Install test dependencies
      command: |
        cd /app
        poetry install --no-root --with test
  - run:
      name: Pytest
      command: |
        . /root/.cache/pypoetry/virtualenvs/*/bin/activate
        cd /app
        pytest .

jobs:
  build_and_push:
    resource_class: large
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Update package manager
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt-get -y install rsync
      - run:
          name: Sync common code
          command: ./scripts/sync
      - run:
          name: Build images from docker-compose.yml
          command: docker compose -f production-compose.yml build
      - run:
          name: Tag images
          command: |
            IMAGES=(identity reader reviewer administrator)
            for IMAGE in "${IMAGES[@]}"; do
              HASH_TAG="${IMAGE}-${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
              LATEST_TAG="${IMAGE}-${CIRCLE_BRANCH}-latest"

              docker tag "project_be-${IMAGE}:latest" "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${HASH_TAG}"
              docker tag "project_be-${IMAGE}:latest" "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${LATEST_TAG}"
            done

            HASH_TAG="api-${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
            LATEST_TAG="api-${CIRCLE_BRANCH}-latest"
            docker tag "project_api:latest" "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${HASH_TAG}"
            docker tag "project_api:latest" "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${LATEST_TAG}"
      - run:
          name: Login to DockerHub
          command: docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_ACCESS_TOKEN}"
      - run:
          name: Push images
          command: |
            IMAGES=(identity reader reviewer administrator)
            for IMAGE in "${IMAGES[@]}"; do
              HASH_TAG="${IMAGE}-${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
              LATEST_TAG="${IMAGE}-${CIRCLE_BRANCH}-latest"

              docker push "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${HASH_TAG}"
              docker push "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${LATEST_TAG}"
            done

            HASH_TAG="api-${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
            LATEST_TAG="api-${CIRCLE_BRANCH}-latest"
            docker push "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${HASH_TAG}"
            docker push "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${LATEST_TAG}"

  black-identity:
    resource_class: small
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:identity-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *black-steps

  black-administrator:
    resource_class: small
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:administrator-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *black-steps

  black-reviewer:
    resource_class: small
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:reviewer-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *black-steps

  black-reader:
    resource_class: small
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:reader-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *black-steps

  pytest-identity:
    resource_class: small
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:identity-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *pytest-steps

  pytest-administrator:
    resource_class: small
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:administrator-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *pytest-steps

  pytest-reviewer:
    resource_class: small
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:reviewer-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *pytest-steps

  pytest-reader:
    resource_class: small
    docker:
      - image: ${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:reader-${CIRCLE_BRANCH}-latest
        auth: *docker-auth
    steps: *pytest-steps

workflows:
  everything:
    jobs:
      - hold:
          type: approval
      - build_and_push:
          requires:
            - hold
      - black-identity:
          requires:
            - build_and_push
      - black-administrator:
          requires:
            - build_and_push
      - black-reviewer:
          requires:
            - build_and_push
      - black-reader:
          requires:
            - build_and_push
      - pytest-identity:
          requires:
            - build_and_push
      - pytest-administrator:
          requires:
            - build_and_push
      - pytest-reviewer:
          requires:
            - build_and_push
      - pytest-reader:
          requires:
            - build_and_push
