version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Echo system information
          command: |
            uname -a
            echo
            docker version
            echo
            ls
            echo
            pwd
      - run:
          name: Update package manager
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt-get -y install rsync
      - run:
          name: Sync common code
          command: ./scripts/sync
      - run:
          name: Build images from docker-compose.yml
          command: docker compose -f production-compose.yml build
      - run:
          name: Tag images
          command: |
            IMAGES=(api be-identity be-reader be-reviewer be-administrator)

            for IMAGE in "${IMAGES[@]}"; do
              TAG="${IMAGE}-${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
              docker tag "project_${IMAGE}:latest" "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${TAG}"

              TAG="${IMAGE}-${CIRCLE_BRANCH}-latest"
              docker tag "project_${IMAGE}:latest" "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${TAG}"
            done
      - run:
          name: Login to DockerHub
          command: docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_ACCESS_TOKEN}"
      - run:
          name: Push images
          command: |
            IMAGES=(api be-identity be-reader be-reviewer be-administrator)

            for IMAGE in "${IMAGES[@]}"; do
              TAG="${IMAGE}-${CIRCLE_BRANCH}-$(git rev-parse --short HEAD)"
              docker push "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${TAG}"

              TAG="${IMAGE}-${CIRCLE_BRANCH}-latest"
              docker push "${DOCKERHUB_USER}/${CIRCLE_PROJECT_REPONAME}:${TAG}"
            done

workflows:
  build_test_push:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - main
      - build_and_push:
          filters:
            branches:
              only:
                - main
          requires:
            - hold
