# pylint: disable=no-member,invalid-name,unused-import

"""UserRole

Revision ID: 4e162e80fbba
Revises: f8bfefd4b530
Create Date: 2022-07-20 10:27:09.711761

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_utils


# revision identifiers, used by Alembic.
revision = "4e162e80fbba"
down_revision = "f8bfefd4b530"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userrole",
        sa.Column(
            "id",
            fastapi_utils.guid_type.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", fastapi_utils.guid_type.GUID(), nullable=False),
        sa.Column("role_id", fastapi_utils.guid_type.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id"),
    )
    op.create_index(op.f("ix_userrole_user_id"), "userrole", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userrole_user_id"), table_name="userrole")
    op.drop_table("userrole")
    # ### end Alembic commands ###
