#!/usr/bin/env bash

BACKENDS=(identity reader reviewer administrator)
DIRECTORIES=(common)
FILES=(Dockerfile .dockerignore mypy.ini .pylintrc activate)

for BACKEND in "${BACKENDS[@]}"
do
  TARGET=${BACKEND}

  for DIRECTORY in "${DIRECTORIES[@]}"
  do
    rsync -v -r -d --delete --delete-excluded common/${DIRECTORY} ${TARGET}
  done

  for FILE in "${FILES[@]}"
  do
    cp -v common/${FILE} ${TARGET}
  done
done

# These three services share a data model, but identity has its own.
BACKENDS=(reader reviewer administrator)
DIRECTORIES=(database)

for BACKEND in "${BACKENDS[@]}"
do
  TARGET=${BACKEND}

  for DIRECTORY in "${DIRECTORIES[@]}"
  do
    rsync -v -r -d --delete --delete-excluded common/${DIRECTORY} ${TARGET}
  done
done

# reader is unauthenticated
echo
echo "removing unused files..."
rm -fv reader/common/services/authorization.py
rm -rfv reader/database/migrations
rm -rfv reviewer/database/migrations
