#!/usr/bin/env bash

set -eo pipefail

BACKENDS=(identity reader reviewer administrator)
DIRECTORIES=(common)
FILES=(Dockerfile .dockerignore mypy.ini .pylintrc echo_activate_path install-poetry.py nginx.conf create-database.sh migrate.sh entrypoint.sh)

for BACKEND in "${BACKENDS[@]}"
do
  TARGET=${BACKEND}

  for DIRECTORY in "${DIRECTORIES[@]}"
  do
    rsync -avrd --delete --delete-excluded core/${DIRECTORY} ${TARGET}
  done

  for FILE in "${FILES[@]}"
  do
    cp -av core/${FILE} ${TARGET}
  done
done

# These three services share a data model, but identity has its own.
BACKENDS=(reader reviewer administrator)
DIRECTORIES=(database)

for BACKEND in "${BACKENDS[@]}"
do
  TARGET=${BACKEND}

  for DIRECTORY in "${DIRECTORIES[@]}"
  do
    rsync -avrd --delete --delete-excluded core/${DIRECTORY} ${TARGET}
  done
done

# reader is unauthenticated
echo
echo "removing unused files..."
rm -rfv reader/database/migrations
rm -rfv reviewer/database/migrations
rm -fv {reader,reviewer}/{migrate,create-database}.sh